export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_INDIVIDUAL_CONTACT = 'GET_INDIVIDUAL_CONTACT';
export const GET_FAV_CONTACT = 'GET_FAV_CONTACT';
export const SET_FAV_CONTACT = 'SET_FAV_CONTACT';
